window.INNOCORE_CONTENT = {
  ko: {
    nav: [
      { label: "펠로우 채용 공고", href: "https://www.innocore.or.kr/dgist/notice/sub01", sameTab: true },
      { label: "사업단", href: "#about" },
      { label: "연구영역", href: "#research" },
      { label: "Fellow 연구지원", href: "#fellows" },
      { label: "Fellow 소개", href: "./fellows.html" },
      { label: "멘토", href: "#mentors" },
    ],
    headerCta: "펠로우 채용 공고",
    heroEyebrow: "DGIST InnoCORE | 에너지 소재 상용화 AX 연구단",
    heroTitle: "연구실에서 양산까지",
    heroLead:
      "E-MatAX는 에너지 소재의 스케일업 병목을 실험, 분석, AI, 검증의 순환으로 풀어내는 Fellow 주도형 연구 플랫폼입니다.",
    heroPrimary: "펠로우 채용 공고",
    heroSecondary: "연구영역 보기",
    facts: [
      { value: "Energy", label: "생산 · 전환 · 저장 소재" },
      { value: "AX", label: "소재-공정 AI 플랫폼" },
      { value: "Co-Lab", label: "DGIST · 대학 · 산업 협업" },
      { value: "5 Years", label: "최대 5년 성장 트랙" },
    ],
    howApplyKicker: "How to Apply",
    howApplyTitle: "Research Fellow 모집 안내",
    howApplyLead:
      "공식 모집 공고에서 지원 자격과 일정을 확인하고, 관심 연구영역의 멘토와 연구 적합성을 논의할 수 있습니다.",
    howApply: [
      { title: "1. 모집 공고 확인", body: "지원 자격, 제출서류, 전형 일정, 계약 조건을 공식 공고에서 확인합니다." },
      { title: "2. 연구영역 매칭", body: "에너지 저장, 전환, 생산, 소재-공정 AI 중 본인의 전문성과 맞는 연구 축을 선택합니다." },
      { title: "3. 멘토 사전 상담", body: "관심 연구영역과 연결되는 교수진의 연구실 정보를 확인하고 연구 적합성을 논의합니다." },
      { title: "4. 지원서 제출", body: "공식 공고 또는 InnoCORE Job Fair 안내에 따라 지원서를 제출합니다." },
    ],
    requirementsTitle: "지원 요건",
    requirements: [
      "이공계 박사학위 소지자 또는 취득 예정자",
      "박사학위 취득 후 5년 이내를 원칙으로 하되, 탁월한 역량 보유자는 예외 심의 가능",
      "전일제 박사후연구원 임용",
      "1년 단위 계약, 평가 후 최대 5년까지 재계약 가능",
      "외국인은 E-3 등 연구활동 비자 발급 요건 충족 필요",
    ],
    aboutKicker: "Why E-MatAX",
    aboutTitle: "상용화 성능을 AX로 다시 설계",
    aboutBody1:
      "에너지 소재는 실험실에서 확보한 성능이 파일럿 또는 양산 전환 과정에서 약화되는 경우가 많습니다. E-MatAX는 소재 조성, 공정 조건, 분석 데이터, AI 모델을 하나의 스케일업 문제로 다룹니다.",
    aboutBody2:
      "InnoCORE Fellow는 연구의 연결축입니다. 도메인 멘토, AI 멘토, 산업 파트너, 분석 인프라를 연결하며 연구성과가 논문을 넘어 검증과 기술이전으로 이어지도록 이끕니다.",
    centerKicker: "About the Center",
    centerTitle: "에너지 소재 상용화 AX 연구단",
    centerLead:
      "E-MatAX는 에너지 소재 상용화 병목을 AX로 줄이기 위해 DGIST, 국내 주요 대학, 산업 파트너를 연결하는 InnoCORE 연구단입니다.",
    director: {
      kicker: "Chief / Research Director",
      name: "Su-mi Hur",
      title: "허수미 교수 | DGIST 에너지공학과",
      body:
        "허수미 연구단장은 에너지 소재, 공정 데이터, AI 모델, 검증 인프라가 하나의 연구 흐름으로 연결되도록 E-MatAX의 연구 방향과 협력 체계를 이끕니다.",
    },
    centerDetails: [
      { label: "Center Name", value: "Center for Energy Materials Commercialization through AI Transformation (AX)" },
      { label: "Korean Name", value: "에너지 소재 상용화 AX 연구단" },
      { label: "Short Name", value: "E-MatAX" },
      { label: "Project Period", value: "Phase I: 2026.05-2028.12 / Phase II: 2029.01-2030.12" },
    ],
    teamsTitle: "Research Teams",
    teams: [
      { title: "Team 1", body: "Energy Storage Materials" },
      { title: "Team 2", body: "Energy Conversion Materials" },
      { title: "Team 3", body: "Energy Production Materials" },
      { title: "Team 4", body: "Materials-Process AI Platform" },
    ],
    relatedLinksTitle: "Related Links",
    relatedLinks: [
      { label: "E-MatAX Research Center", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
      { label: "DGIST InnoCORE notices", href: "https://www.innocore.or.kr/dgist/notice/sub01" },
      { label: "InnoCORE Global Job Fair", href: "https://www.innocore-jobfair.com/" },
    ],
    researchKicker: "Research Portfolio",
    researchTitle: "상용화를 여는 4대 AX 축",
    researchLead: "저장, 전환, 생산 소재와 소재-공정 AI 플랫폼을 연결해 실험실 성능이 제조 단계에서도 유지되도록 연구합니다.",
    research: [
      {
        title: "에너지 저장 소재",
        problem: "배터리 소재는 공정이 커질수록 균일도, 열화, 계면 안정성 문제가 커집니다.",
        solution: "전극, 전해질, 급속충전, 건식 전극 공정 데이터를 연결해 예측 가능한 스케일업 조건을 찾습니다.",
      },
      {
        title: "에너지 전환 소재",
        problem: "촉매와 전기화학 시스템은 실험 조건과 실제 운전 조건 사이의 차이가 큽니다.",
        solution: "반응, 구조, 열화 데이터를 함께 학습해 고효율·저열화 전환 소재 개발을 앞당깁니다.",
      },
      {
        title: "에너지 생산 소재",
        problem: "태양광 등 생산 소재는 효율, 수명, 제조 재현성을 동시에 확보해야 합니다.",
        solution: "소재 설계와 공정 최적화를 AI 기반으로 반복해 생산 단계의 성능 안정성을 높입니다.",
      },
      {
        title: "소재-공정 AI 플랫폼",
        problem: "연구실마다 데이터가 흩어지면 스케일업 예측과 재현 검증이 어려워집니다.",
        solution: "Descriptor, 물리 기반 AI 모델, 데이터 파이프라인, 검증 라이브러리를 통합합니다.",
      },
    ],
    processKicker: "Research Workflow",
    processTitle: "합성·측정·예측·검증",
    processLead:
      "Fellow는 하나의 소재 문제를 정의하고 실험 데이터와 공정 데이터를 연결합니다. AI 예측 결과는 다시 파일럿 검증으로 돌아가며 연구의 다음 조건을 만듭니다.",
    process: [
      "문제 정의",
      "실험 설계",
      "정밀 분석",
      "AI 모델링",
      "스케일업 검증",
      "산업 연계",
    ],
    fellowsKicker: "For Fellows",
    fellowsTitle: "Fellow 주도 연구, 사업단 지원",
    fellowsLead:
      "교수 보조형 포닥이 아닌, Fellow 주도형 연구 체계",
    fellowDirectoryCta: "Fellow 소개 보기",
    support: [
      { title: "듀얼 멘토링", body: "도메인 멘토와 AI 멘토가 함께 연구 방향을 설계하고 AX 역량을 강화합니다." },
      { title: "연구 인프라", body: "DGIST의 분석, 제작, 컴퓨팅, 파일럿 연계 인프라를 연구 목적에 맞게 활용합니다." },
      { title: "산학연 Co-Lab", body: "파트너 대학, 연구기관, 산업 파트너와 함께 실증과 기술이전 가능성을 높입니다." },
      { title: "정주 지원", body: "비자, 온보딩, 생활 정착 지원으로 글로벌 연구자가 빠르게 연구에 집중할 수 있게 돕습니다." },
    ],
    fellowPageKicker: "Fellow Directory",
    fellowPageTitle: "E-MatAX Fellows",
    fellowPageLead:
      "E-MatAX Fellow의 소속, 현재 PI, 연구분야, 연구 소개를 한곳에서 볼 수 있는 소개 페이지입니다.",
    fellowProfileLabels: {
      currentPi: "현재 PI",
      researchArea: "연구 분야",
      affiliation: "소속",
      status: "상태",
    },
    fellowProfiles: [
      {
        "name": "안지훈",
        "nameEn": "Jihun Ahn",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "고분자 시스템의 자기조립을 계산과학으로 해석하고, 딥러닝 기반 물성 예측·역설계와 EUV 리소그래피용 고분자 설계를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Taylor Derrick Allan",
        "nameEn": "Derrick Allan Taylor",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이종수 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "가시광·적외선 양자점의 콜로이드 합성, 리간드·결함 제어와 친환경 용액 공정을 통해 에너지·광전자 소자를 위한 반도체 나노결정을 개발합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Wang Wenxin",
        "nameEn": "Wenxin Wang",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이종민 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "메탈렌과 메조다공성 금속 촉매를 설계해 수전해, 전기화학적 암모니아 합성, 선택적 수소화와 폐플라스틱 업사이클링을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Vo Pham Hoang Huy",
        "nameEn": "Vo Pham Hoang Huy",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김대환 책임연구원 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "Sb2Se3 및 페로브스카이트 박막 태양전지의 소재·소자 구조를 개발하고, 대면적 제조와 AI 기반 공정 최적화를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "유정훈",
        "nameEn": "Jeong-Hoon Yu",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김순현 책임연구원 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "리튬-황 전지용 황 호스트·기능성 분리막·촉매와 다공성 탄소 소재를 설계하고, 전극 및 셀 수준의 전기화학 성능을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "이운학",
        "nameEn": "Un-Hak Lee",
        "status": "InnoCORE Research Fellow",
        "currentPi": "고서진 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "초저밴드갭 유기 반도체와 공액 고분자를 합성해 단파적외선 유기 광검출기 및 투명·반투명 태양전지 소재를 개발합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Li Shi",
        "nameEn": "Shi Li",
        "status": "InnoCORE Research Fellow",
        "currentPi": "양지웅 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "양자점 광전자소자를 중심으로 유연·웨어러블 광검출기와 결함 제어형 광전기화학 수소생산 소재를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "송현석",
        "nameEn": "Hyunseok Song",
        "status": "InnoCORE Research Fellow",
        "currentPi": "송현철 교수 (고려대학교)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "강유전·다강체 박막과 인공 상경계를 설계해 에너지 하베스팅·저장 소자, 자가발전 센서와 IoT 응용을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Zhao Pin",
        "nameEn": "Pin Zhao",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이주혁 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "2차원 압전 소재와 탄소나노튜브 헤테로구조의 전기·광전자 특성을 제어해 센서, 광검출기와 에너지 하베스팅 소자를 개발합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "조완수",
        "nameEn": "Wansu Cho",
        "status": "InnoCORE Research Fellow",
        "currentPi": "박치영 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "다공성 고분자와 COF-탄소 나노하이브리드를 설계해 광촉매 수소생산, 수처리 및 오염물 흡착 소재를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "이다슬",
        "nameEn": "Daseul Lee",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김한슬 교수 (충북대학교)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "무연·키랄 페로브스카이트와 금속-유기 구조체를 합성하고, 가스센서·광검출기·발광소자·메모리 소자 응용을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Muralidharan Vageesh",
        "nameEn": "Vageesh M",
        "status": "InnoCORE Research Fellow",
        "currentPi": "남기태 교수 (서울대학교)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "나노·단일원자 촉매와 전기촉매를 이용해 지속가능한 유기합성, 탈수소화·수소화 및 C-H 활성화 반응을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "김수환",
        "nameEn": "Suhwan Kim",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이용민 교수 (연세대학교)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "충전식 전지의 디지털 트윈과 동적 시뮬레이션을 구축해 전극·분리막의 구조 변형, 계면 진화와 고장 메커니즘을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "김홍수",
        "nameEn": "Hong Soo Kim",
        "status": "InnoCORE Research Fellow",
        "currentPi": "인수일 교수 (DGIST)",
        "researchArea": "에너지 저장 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "광촉매 CO2 전환과 인공광합성, 베타볼타익 전지 및 마이크로·나노 전기화학 바이오소자를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "엄세원",
        "nameEn": "Sewon Eom",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이호춘 교수 (DGIST)",
        "researchArea": "에너지 저장 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "리튬·나트륨 금속, 무음극 및 리튬-황 전지용 전해질을 설계하고 분광·이미징 기반 계면 열화와 셀 고장을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Héctor Allan Pérez-Ramírez",
        "nameEn": "Héctor Allan Pérez-Ramírez",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "분자동역학을 활용해 열응답성 고분자, 블록공중합체 자기조립과 저유전 고분자의 구조·수송 특성을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Manoj Kumar Maurya",
        "nameEn": "Manoj Kumar Maurya",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "분자동역학과 머신러닝으로 연성물질의 상분리와 고분자 네트워크의 기계·열 특성을 계산하고 소재 거동을 예측합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "변아송",
        "nameEn": "Asong Byun",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김승현 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "금속-유기 구조체와 비정질 다공성·중공 소재를 설계해 선택적 흡착과 촉매 반응을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "박영진",
        "nameEn": "",
        "status": "InnoCORE Research Fellow",
        "currentPi": "박인철 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "NCM·LFP 양극과 파일럿 셀 제조공정을 개발하고, 2차원 소재 합성·전기촉매 경험을 바탕으로 배터리 공정의 AI 품질진단을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Sangram Keshari Mohanty",
        "nameEn": "Sangram Keshari Mohanty",
        "status": "InnoCORE Research Fellow",
        "currentPi": "홍승태 교수 (DGIST)",
        "researchArea": "에너지 저장 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "리튬·나트륨 전지용 고성능 양극 소재를 합성하고, operando XRD와 EQCM을 이용해 전극 구조와 계면 반응을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "마현종",
        "nameEn": "Hyeonjong Ma",
        "status": "InnoCORE Research Fellow",
        "currentPi": "양지웅 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "in situ TEM과 첨단 분광·구조 분석으로 반도체 나노결정의 구조 진화와 열화 메커니즘을 규명하고 안정성 설계를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Srinivasu Vinjamuri",
        "nameEn": "Srinivasu Vinjamuri",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김승현 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "광레독스 촉매와 고리 변형 에너지를 활용한 원격 C-H 기능화 및 고부가 유기분자의 다단계 합성법을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "강욱중",
        "nameEn": "Uk Jung Kang",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "DFT, 머신러닝 원자간 포텐셜과 분자동역학을 결합해 에너지 소재와 전기촉매의 전자구조·원자 수준 거동을 계산합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "한상훈",
        "nameEn": "Sanghun Han",
        "status": "InnoCORE Research Fellow",
        "currentPi": "최종민 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "페로브스카이트 양자점의 표면 리간드와 고체 안정성을 제어해 고효율 광전소자, 광촉매 및 대면적 양자점 잉크 공정을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Jingcheng Wu",
        "nameEn": "Jingcheng Wu",
        "status": "InnoCORE Research Fellow",
        "currentPi": "최창혁 교수 (POSTECH)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "바이오매스 플랫폼 분자의 전기화학 전환과 환원 반응을 결합한 paired electrolysis를 설계해 고부가 화학물질 생산을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      }
    ],
    openingsKicker: "Fellow Recruitment",
    openingsTitle: "펠로우 채용 공고",
    openingsLead:
      "공식 연구단 공고로 담기 어려운 연구실별 모집상태, 세부 주제, 선호 역량을 한곳에서 확인합니다.",
    piOpenings: [
      {
        id: "dong-hae-ho",
        status: "적극 모집 중",
        title: "액체금속 복합소재 연구 Fellow 모집",
        pi: "호동해 교수",
        lab: "EMDP Lab",
        area: "액체금속 복합소재 연구",
        fit:
          "액체금속 기반 composite 연구, 기계적 분석, 전기·열전도도 분석을 수행할 수 있는 연구자를 찾습니다. 관련 학위, 연구 열정, 세밀한 관찰력, 자유로운 연구 분위기에 맞는 태도를 중요하게 봅니다.",
        timeline: "2027년 여름",
        contactLabel: "문의: hodh123@gmail.com",
        contactHref: "mailto:hodh123@gmail.com",
        heroImage: "./assets/pi-openings/dong-hae-ho-header.png",
        flyer: "./assets/pi-openings/dong-hae-ho-flyer.png",
      },
    ],
    mentorsKicker: "Mentor List",
    mentorsTitle: "E-MatAX 멘토 그룹",
    mentorsLead:
      "DGIST와 국내 주요 대학의 참여 교수진이 4대 연구축별로 에너지 소재, 공정, AI, 분석, 검증 연구를 함께 이끕니다.",
    mentorColumns: ["채용상태", "연구축", "역할", "성명", "English Name", "소속", "학과/부서", "Website"],
    mentorRecruitingStatus: "적극 채용중",
    mentorDefaultRecruitingStatus: "active",
    mentorRecruitingStatusLabels: {
      active: "적극 채용중",
      inactive: "채용중 아님",
    },
    mentorRecruitingStatusOptions: [
      { value: "active", label: "적극 채용중" },
      { value: "inactive", label: "채용중 아님" },
    ],
    mentorRecruitingStatuses: {
      "허수미 교수": "active",
      "고서진 교수": "active",
      "김승현 교수": "active",
      "김영규 교수": "active",
      "김운혁 교수": "active",
      "김진수 교수": "active",
      "김찬연 교수": "active",
      "박인철 교수": "active",
      "박치영 교수": "active",
      "상가라쥬 샨무감 교수": "active",
      "양지웅 교수": "active",
      "이윤구 교수": "active",
      "이종민 교수": "active",
      "이종수 교수": "active",
      "이주혁 교수": "active",
      "이호춘 교수": "active",
      "인수일 교수": "active",
      "장윤희 교수": "active",
      "최승호 교수": "active",
      "최종민 교수": "active",
      "호동해 교수": "active",
      "홍승태 교수": "active",
      "강준희 교수": "active",
      "김대환 책임연구원": "active",
      "김순현 책임연구원": "active",
      "김한슬 교수": "active",
      "남기태 교수": "active",
      "박해선 교수": "active",
      "송현철 교수": "active",
      "이용민 교수": "active",
      "임종우 교수": "active",
      "임종철 교수": "active",
      "최창혁 교수": "active"
    },
    mentorAreas: {
      "허수미 교수": "소재-공정 AI 플랫폼",
      "장윤희 교수": "소재-공정 AI 플랫폼",
      "최승호 교수": "소재-공정 AI 플랫폼",
      "박해선 교수": "소재-공정 AI 플랫폼",
      "강준희 교수": "소재-공정 AI 플랫폼",
      "박인철 교수": "소재-공정 AI 플랫폼",
      "김한슬 교수": "소재-공정 AI 플랫폼",
      "이용민 교수": "소재-공정 AI 플랫폼",
      "이주혁 교수": "에너지 생산 소재",
      "고서진 교수": "에너지 생산 소재",
      "최종민 교수": "에너지 생산 소재",
      "호동해 교수": "에너지 생산 소재",
      "이윤구 교수": "에너지 생산 소재",
      "김대환 책임연구원": "에너지 생산 소재",
      "이종수 교수": "에너지 생산 소재",
      "양지웅 교수": "에너지 생산 소재",
      "송현철 교수": "에너지 생산 소재",
      "임종철 교수": "에너지 생산 소재",
      "김찬연 교수": "에너지 전환 소재",
      "상가라쥬 샨무감 교수": "에너지 전환 소재",
      "박치영 교수": "에너지 전환 소재",
      "이종민 교수": "에너지 전환 소재",
      "김순현 책임연구원": "에너지 전환 소재",
      "김승현 교수": "에너지 전환 소재",
      "남기태 교수": "에너지 전환 소재",
      "최창혁 교수": "에너지 전환 소재",
      "홍승태 교수": "에너지 저장 소재",
      "김운혁 교수": "에너지 저장 소재",
      "인수일 교수": "에너지 저장 소재",
      "이호춘 교수": "에너지 저장 소재",
      "김진수 교수": "에너지 저장 소재",
      "김영규 교수": "에너지 저장 소재",
      "임종우 교수": "에너지 저장 소재",
    },
    mentors: [
      { role: "Research Director", name: "허수미 교수", nameEn: "Su-Mi Hur", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sml-dgist.vercel.app/" },
      { role: "Mentor", name: "고서진 교수", nameEn: "Seo-Jin Ko", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://hodl.dgist.ac.kr/" },
      { role: "Mentor", name: "김승현 교수", nameEn: "Seunghyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/seunghyeonkimlab/" },
      { role: "Mentor", name: "김영규 교수", nameEn: "Younggyu Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://younggyukim.com" },
      { role: "Mentor", name: "김운혁 교수", nameEn: "Un-Hyuck Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://phduhkim.wixsite.com/my-site-2" },
      { role: "Mentor", name: "김진수 교수", nameEn: "Jinsoo Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://bdpl-website.web.app/" },
      { role: "Mentor", name: "김찬연 교수", nameEn: "Chanyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/ck-researchgroup" },
      { role: "Mentor", name: "박인철 교수", nameEn: "Inchul Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://ai4m.vercel.app" },
      { role: "Mentor", name: "박치영 교수", nameEn: "Chiyoung Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cplab2019.wixsite.com/cplab" },
      { role: "Mentor", name: "상가라쥬 샨무감 교수", nameEn: "Sangaraju Shanmugam", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sangarajus.wixsite.com/shanmugam" },
      { role: "Mentor", name: "양지웅 교수", nameEn: "Jiwoong Yang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://www.jiwoongyang.net" },
      { role: "Mentor", name: "이윤구 교수", nameEn: "Youngu Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://kjy950123.wixsite.com/opel" },
      { role: "Mentor", name: "이종민 교수", nameEn: "Jong-Min Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/jmleedgist/%ED%99%88" },
      { role: "Mentor", name: "이종수 교수", nameEn: "Jong-Soo Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://jslee.dgist.ac.kr/" },
      { role: "Mentor", name: "이주혁 교수", nameEn: "Ju-Hyuck Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://juhyucklee1107.wixsite.com/website" },
      { role: "Mentor", name: "이호춘 교수", nameEn: "Hochun Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://dukelee5.wixsite.com/else" },
      { role: "Mentor", name: "인수일 교수", nameEn: "Suil In", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://insuil.dgist.ac.kr" },
      { role: "Mentor", name: "장윤희 교수", nameEn: "Yun Hee Jang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cmmm.dgist.ac.kr" },
      { role: "Mentor", name: "최승호 교수", nameEn: "Seungho Choe", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://seunghochoe.netlify.app/" },
      { role: "Mentor", name: "최종민 교수", nameEn: "Jongmin Choi", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/choisresearchgroup/home" },
      { role: "Mentor", name: "호동해 교수", nameEn: "Dong Hae Ho", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://emdplab.github.io/" },
      { role: "Mentor", name: "홍승태 교수", nameEn: "Seung-Tae Hong", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sthong.dgist.ac.kr" },
      { role: "Mentor", name: "강준희 교수", nameEn: "Joonhee Kang", affiliation: "Pusan National University", department: "School of Transdisciplinary Engineering", url: "https://sites.google.com/view/kanggroup/home" },
      { role: "Mentor", name: "김대환 책임연구원", nameEn: "Dae-Hwan Kim", affiliation: "DGIST", department: "Department of Interdisciplinary Studies", url: "" },
      { role: "Mentor", name: "김순현 책임연구원", nameEn: "Soonhyun Kim", affiliation: "DGIST", department: "Division of Energy & Environmental Technology", url: "" },
      { role: "Mentor", name: "김한슬 교수", nameEn: "Han Seul Kim", affiliation: "Chungbuk National University", department: "Department of Advanced Materials Engineering", url: "https://atomlab.co.kr/" },
      { role: "Mentor", name: "남기태 교수", nameEn: "Ki Tae Nam", affiliation: "Seoul National University", department: "Department of Materials Science and Engineering", url: "https://www.nkitae.org/" },
      { role: "Mentor", name: "박해선 교수", nameEn: "Haesun Park", affiliation: "Chung-Ang University", department: "School of Integrative Engineering", url: "https://midas-cau.netlify.app/" },
      { role: "Mentor", name: "송현철 교수", nameEn: "Hyun-Cheol Song", affiliation: "Korea University", department: "Department of Materials Science and Engineering", url: "http://eclab.korea.ac.kr/" },
      { role: "Mentor", name: "이용민 교수", nameEn: "Yong Min Lee", affiliation: "Yonsei University", department: "Chemical and Biomolecular Engineering / Battery Engineering", url: "http://batterylab.yonsei.ac.kr/" },
      { role: "Mentor", name: "임종우 교수", nameEn: "Jongwoo Lim", affiliation: "Seoul National University", department: "Department of Chemistry", url: "https://www.jwlimgroup.com" },
      { role: "Mentor", name: "임종철 교수", nameEn: "Jongchul Lim", affiliation: "Chungnam National University", department: "Graduate School of Energy Science and Technology", url: "https://jongchullim.wixsite.com/jclim" },
      { role: "Mentor", name: "최창혁 교수", nameEn: "Chang Hyuck Choi", affiliation: "POSTECH", department: "Department of Chemistry", url: "https://www.ecatlab.com/" },
    ],
    newsKicker: "Recent News",
    newsTitle: "공고 및 행사 소식",
    newsLead:
      "Research Fellow 모집 공고, 글로벌 Job Fair 및 E-MatAX 연구 행사 소식을 확인할 수 있습니다.",
    news: [
      {
        "date": "2026.07.20",
        "title": "E-MatAX Luncheon Seminar | 이태훈 교수·E-MatAX Fellow",
        "description": "DGIST 이태훈 교수님과 E-MatAX Postdoctoral Fellow가 함께 런천 세미나를 진행했습니다. 시뮬레이션과 AI 계산과의 징검다리 역할을 할 수 있는 다양한 방법론에 대해 알아보는 자리였습니다.",
        "href": "",
        "images": [
          {
            "thumb": "./assets/news/2026-07-20-luncheon-seminar-thumb.jpg",
            "full": "./assets/news/2026-07-20-luncheon-seminar.jpg"
          }
        ]
      },
      {
        "date": "2026.07.06",
        "title": "E-MatAX Luncheon Seminar | 김영규 교수·E-MatAX Fellow",
        "description": "DGIST 김영규 교수님과 Fellow 박사와 함께 Luncheon 세미나를 진행하였습니다. 실험과 AI 를 이을 수 있는 다양한 방법론에 대한 심도깊은 세미나였습니다",
        "href": "",
        "images": [
          {
            "thumb": "./assets/news/2026-07-06-luncheon-opening-thumb.jpg",
            "full": "./assets/news/2026-07-06-luncheon-opening.jpg"
          },
          {
            "thumb": "./assets/news/2026-07-06-luncheon-kim-younggyu-thumb.jpg",
            "full": "./assets/news/2026-07-06-luncheon-kim-younggyu.jpg"
          },
          {
            "thumb": "./assets/news/2026-07-06-luncheon-audience-thumb.jpg",
            "full": "./assets/news/2026-07-06-luncheon-audience.jpg"
          }
        ]
      },
      {
        "date": "2026.06",
        "title": "Europe InnoCORE Global AI Postdoctoral Job Fair",
        "description": "",
        "href": "https://www.innocore-jobfair.com/",
        "images": []
      },
      {
        "date": "2026.05",
        "title": "US InnoCORE Global AI Postdoctoral Job Fair",
        "description": "",
        "href": "https://www.innocore-jobfair.com/",
        "images": []
      },
      {
        "date": "상시",
        "title": "DGIST InnoCORE Notice Board",
        "description": "",
        "href": "https://www.innocore.or.kr/dgist/notice/sub01",
        "images": []
      }
    ],
    applyKicker: "Fellow Recruitment",
    applyTitle: "AX로 실험실에서 양산까지",
    applyLead:
      "E-MatAX와 함께 에너지 소재 상용화 AX를 만들어갈 Research Fellow를 모집합니다. 공식 모집 공고와 문의 채널을 통해 지원 절차를 확인해주세요.",
    applyActions: [
      { label: "펠로우 채용 공고 바로가기", href: "https://www.innocore.or.kr/dgist/notice/sub01", sameTab: true },
      { label: "문의: innocore@dgist.ac.kr", href: "mailto:innocore@dgist.ac.kr" },
      { label: "E-MatAX 연구단 소개", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
    ],
    footerText:
      "DGIST InnoCORE E-MatAX Research Center",
  },
  en: {
    nav: [
      { label: "Fellow Notice", href: "https://www.innocore.or.kr/dgist/notice/sub01", sameTab: true },
      { label: "About", href: "#about" },
      { label: "Research", href: "#research" },
      { label: "Fellow Support", href: "#fellows" },
      { label: "Fellow Directory", href: "./fellows.html" },
      { label: "Mentors", href: "#mentors" },
    ],
    headerCta: "Fellow Notice",
    heroEyebrow: "DGIST InnoCORE | E-MatAX Research Center",
    heroTitle: "Fellow-led AX, from lab to production",
    heroLead:
      "E-MatAX reduces scale-up bottlenecks in energy production, conversion, and storage materials through an experiment-analysis-AI-validation loop while training next-generation convergence researchers.",
    heroPrimary: "Fellow Recruitment",
    heroSecondary: "Research Scope",
    facts: [
      { value: "Energy", label: "Production, conversion, storage" },
      { value: "AX", label: "Materials-process AI platform" },
      { value: "Co-Lab", label: "DGIST, universities, industry" },
      { value: "5 Years", label: "Up to five-year growth track" },
    ],
    howApplyKicker: "How to Apply",
    howApplyTitle: "Fellow application guide",
    howApplyLead:
      "Review the notice, choose a research area, and discuss fit with mentors.",
    howApply: [
      { title: "1. Check the notice", body: "Review eligibility, required documents, and timeline through the official announcement and FAQ." },
      { title: "2. Choose a research area", body: "Find the best fit across energy storage, conversion, production, or the materials-process AI platform." },
      { title: "3. Contact mentors", body: "Review labs connected to your research interests and arrange early conversations where appropriate." },
      { title: "4. Submit application", body: "Apply through the finalized official notice or InnoCORE Job Fair channel." },
    ],
    requirementsTitle: "Requirements",
    requirements: [
      "Ph.D. degree in science or engineering, obtained or expected",
      "Generally within five years of Ph.D. conferral, with exceptional-candidate review possible",
      "Full-time postdoctoral appointment",
      "One-year contract, renewable for up to five years subject to evaluation",
      "International applicants must satisfy research visa requirements such as E-3",
    ],
    aboutKicker: "Why E-MatAX",
    aboutTitle: "Scale-up performance with AX",
    aboutBody1:
      "Energy materials often lose lab-scale performance when they move into pilot and manufacturing environments. E-MatAX treats composition, process conditions, characterization data, and AI models as one integrated scale-up problem.",
    aboutBody2:
      "InnoCORE Fellows act as the connective core of research. Fellows link domain mentors, AI mentors, industry partners, and research infrastructure so that outcomes move beyond papers toward validation and technology transfer.",
    centerKicker: "About the Center",
    centerTitle: "E-MatAX Research Center",
    centerLead:
      "E-MatAX connects DGIST, partner universities, and industry to solve energy-materials scale-up bottlenecks.",
    director: {
      kicker: "Chief / Research Director",
      name: "Su-mi Hur",
      title: "Professor, Department of Energy Science and Engineering, DGIST",
      body:
        "The E-MatAX chief leads the center's research direction and collaboration across energy materials, process data, AI models, and validation infrastructure.",
    },
    centerDetails: [
      { label: "Center Name", value: "Energy Materials Commercialization through AI Transformation (AX)" },
      { label: "Korean Name", value: "에너지 소재 상용화 AX 연구단" },
      { label: "Short Name", value: "E-MatAX" },
      { label: "Project Period", value: "Phase I: May 2026-Dec. 2028 / Phase II: Jan. 2029-Dec. 2030" },
    ],
    teamsTitle: "Research Teams",
    teams: [
      { title: "Team 1", body: "Energy Storage Materials" },
      { title: "Team 2", body: "Energy Conversion Materials" },
      { title: "Team 3", body: "Energy Production Materials" },
      { title: "Team 4", body: "Materials-Process AI Platform" },
    ],
    relatedLinksTitle: "Related Links",
    relatedLinks: [
      { label: "E-MatAX Research Center", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
      { label: "DGIST InnoCORE notices", href: "https://www.innocore.or.kr/dgist/notice/sub01" },
      { label: "InnoCORE Global Job Fair", href: "https://www.innocore-jobfair.com/" },
    ],
    researchKicker: "Research Portfolio",
    researchTitle: "Four AX research pillars",
    researchLead: "Storage, conversion, production, and AI-platform research keep lab performance viable at manufacturing scale.",
    research: [
      {
        title: "Energy Storage Materials",
        problem: "Battery materials face uniformity, degradation, and interface stability challenges during scale-up.",
        solution: "We connect electrode, electrolyte, fast-charging, and dry-electrode process data to find predictable scale-up conditions.",
      },
      {
        title: "Energy Conversion Materials",
        problem: "Catalysts and electrochemical systems often show a gap between laboratory tests and real operating conditions.",
        solution: "We jointly learn reaction, structure, and degradation data to accelerate high-efficiency, low-degradation materials.",
      },
      {
        title: "Energy Production Materials",
        problem: "Solar and next-generation production materials must balance efficiency, lifetime, and manufacturing reproducibility.",
        solution: "We iterate AI-driven material design and process optimization to improve performance stability at production scale.",
      },
      {
        title: "Materials-Process AI Platform",
        problem: "Scattered data makes scale-up prediction and reproducibility checks difficult.",
        solution: "We integrate descriptors, physics-informed models, data pipelines, and validation libraries.",
      },
    ],
    processKicker: "Research Workflow",
    processTitle: "Make. Measure. Predict. Validate.",
    processLead:
      "E-MatAX is organized around the research loop, not administrative wording. Fellows define a material problem, connect experiment and process data, use AI prediction, and return the result to pilot-scale validation.",
    process: [
      "Problem framing",
      "Experiment design",
      "Characterization",
      "AI modeling",
      "Scale-up validation",
      "Industry linkage",
    ],
    fellowsKicker: "For Fellows",
    fellowsTitle: "Independent Fellows, structured support",
    fellowsLead:
      "This is a Fellow-led research model, not a standard assistant postdoc track.",
    fellowDirectoryCta: "View Fellows",
    support: [
      { title: "Dual Mentoring", body: "Domain and AI mentors help Fellows strengthen both energy materials expertise and AX capability." },
      { title: "Infrastructure Access", body: "Fellows use DGIST characterization, fabrication, computing, and pilot-linked infrastructure for research goals." },
      { title: "Industry Co-Lab", body: "Partner universities, research institutes, and industry partners increase the chance of demonstration and transfer." },
      { title: "Settlement Support", body: "Visa, onboarding, and relocation support help global researchers focus on research quickly." },
    ],
    fellowPageKicker: "Fellow Directory",
    fellowPageTitle: "E-MatAX Fellows",
    fellowPageLead:
      "A directory page for introducing each E-MatAX Fellow's affiliation, current PI, research area, and research summary.",
    fellowProfileLabels: {
      currentPi: "Current PI",
      researchArea: "Research Area",
      affiliation: "Affiliation",
      status: "Status",
    },
    fellowProfiles: [
      {
        "name": "안지훈",
        "nameEn": "Jihun Ahn",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "고분자 시스템의 자기조립을 계산과학으로 해석하고, 딥러닝 기반 물성 예측·역설계와 EUV 리소그래피용 고분자 설계를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Taylor Derrick Allan",
        "nameEn": "Derrick Allan Taylor",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이종수 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "가시광·적외선 양자점의 콜로이드 합성, 리간드·결함 제어와 친환경 용액 공정을 통해 에너지·광전자 소자를 위한 반도체 나노결정을 개발합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Wang Wenxin",
        "nameEn": "Wenxin Wang",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이종민 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "메탈렌과 메조다공성 금속 촉매를 설계해 수전해, 전기화학적 암모니아 합성, 선택적 수소화와 폐플라스틱 업사이클링을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Vo Pham Hoang Huy",
        "nameEn": "Vo Pham Hoang Huy",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김대환 책임연구원 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "Sb2Se3 및 페로브스카이트 박막 태양전지의 소재·소자 구조를 개발하고, 대면적 제조와 AI 기반 공정 최적화를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "유정훈",
        "nameEn": "Jeong-Hoon Yu",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김순현 책임연구원 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "리튬-황 전지용 황 호스트·기능성 분리막·촉매와 다공성 탄소 소재를 설계하고, 전극 및 셀 수준의 전기화학 성능을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "이운학",
        "nameEn": "Un-Hak Lee",
        "status": "InnoCORE Research Fellow",
        "currentPi": "고서진 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "초저밴드갭 유기 반도체와 공액 고분자를 합성해 단파적외선 유기 광검출기 및 투명·반투명 태양전지 소재를 개발합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Li Shi",
        "nameEn": "Shi Li",
        "status": "InnoCORE Research Fellow",
        "currentPi": "양지웅 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "양자점 광전자소자를 중심으로 유연·웨어러블 광검출기와 결함 제어형 광전기화학 수소생산 소재를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "송현석",
        "nameEn": "Hyunseok Song",
        "status": "InnoCORE Research Fellow",
        "currentPi": "송현철 교수 (고려대학교)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "강유전·다강체 박막과 인공 상경계를 설계해 에너지 하베스팅·저장 소자, 자가발전 센서와 IoT 응용을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Zhao Pin",
        "nameEn": "Pin Zhao",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이주혁 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "2차원 압전 소재와 탄소나노튜브 헤테로구조의 전기·광전자 특성을 제어해 센서, 광검출기와 에너지 하베스팅 소자를 개발합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "조완수",
        "nameEn": "Wansu Cho",
        "status": "InnoCORE Research Fellow",
        "currentPi": "박치영 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "다공성 고분자와 COF-탄소 나노하이브리드를 설계해 광촉매 수소생산, 수처리 및 오염물 흡착 소재를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "이다슬",
        "nameEn": "Daseul Lee",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김한슬 교수 (충북대학교)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "무연·키랄 페로브스카이트와 금속-유기 구조체를 합성하고, 가스센서·광검출기·발광소자·메모리 소자 응용을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Muralidharan Vageesh",
        "nameEn": "Vageesh M",
        "status": "InnoCORE Research Fellow",
        "currentPi": "남기태 교수 (서울대학교)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "나노·단일원자 촉매와 전기촉매를 이용해 지속가능한 유기합성, 탈수소화·수소화 및 C-H 활성화 반응을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "김수환",
        "nameEn": "Suhwan Kim",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이용민 교수 (연세대학교)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "충전식 전지의 디지털 트윈과 동적 시뮬레이션을 구축해 전극·분리막의 구조 변형, 계면 진화와 고장 메커니즘을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "김홍수",
        "nameEn": "Hong Soo Kim",
        "status": "InnoCORE Research Fellow",
        "currentPi": "인수일 교수 (DGIST)",
        "researchArea": "에너지 저장 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "광촉매 CO2 전환과 인공광합성, 베타볼타익 전지 및 마이크로·나노 전기화학 바이오소자를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "엄세원",
        "nameEn": "Sewon Eom",
        "status": "InnoCORE Research Fellow",
        "currentPi": "이호춘 교수 (DGIST)",
        "researchArea": "에너지 저장 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "리튬·나트륨 금속, 무음극 및 리튬-황 전지용 전해질을 설계하고 분광·이미징 기반 계면 열화와 셀 고장을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Héctor Allan Pérez-Ramírez",
        "nameEn": "Héctor Allan Pérez-Ramírez",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "분자동역학을 활용해 열응답성 고분자, 블록공중합체 자기조립과 저유전 고분자의 구조·수송 특성을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Manoj Kumar Maurya",
        "nameEn": "Manoj Kumar Maurya",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "분자동역학과 머신러닝으로 연성물질의 상분리와 고분자 네트워크의 기계·열 특성을 계산하고 소재 거동을 예측합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "변아송",
        "nameEn": "Asong Byun",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김승현 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "금속-유기 구조체와 비정질 다공성·중공 소재를 설계해 선택적 흡착과 촉매 반응을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "박영진",
        "nameEn": "",
        "status": "InnoCORE Research Fellow",
        "currentPi": "박인철 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "NCM·LFP 양극과 파일럿 셀 제조공정을 개발하고, 2차원 소재 합성·전기촉매 경험을 바탕으로 배터리 공정의 AI 품질진단을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Sangram Keshari Mohanty",
        "nameEn": "Sangram Keshari Mohanty",
        "status": "InnoCORE Research Fellow",
        "currentPi": "홍승태 교수 (DGIST)",
        "researchArea": "에너지 저장 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "리튬·나트륨 전지용 고성능 양극 소재를 합성하고, operando XRD와 EQCM을 이용해 전극 구조와 계면 반응을 분석합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "마현종",
        "nameEn": "Hyeonjong Ma",
        "status": "InnoCORE Research Fellow",
        "currentPi": "양지웅 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "in situ TEM과 첨단 분광·구조 분석으로 반도체 나노결정의 구조 진화와 열화 메커니즘을 규명하고 안정성 설계를 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Srinivasu Vinjamuri",
        "nameEn": "Srinivasu Vinjamuri",
        "status": "InnoCORE Research Fellow",
        "currentPi": "김승현 교수 (DGIST)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "광레독스 촉매와 고리 변형 에너지를 활용한 원격 C-H 기능화 및 고부가 유기분자의 다단계 합성법을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "강욱중",
        "nameEn": "Uk Jung Kang",
        "status": "InnoCORE Research Fellow",
        "currentPi": "허수미 교수 (DGIST)",
        "researchArea": "소재-공정 AI 플랫폼",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "DFT, 머신러닝 원자간 포텐셜과 분자동역학을 결합해 에너지 소재와 전기촉매의 전자구조·원자 수준 거동을 계산합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "한상훈",
        "nameEn": "Sanghun Han",
        "status": "InnoCORE Research Fellow",
        "currentPi": "최종민 교수 (DGIST)",
        "researchArea": "에너지 생산 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "페로브스카이트 양자점의 표면 리간드와 고체 안정성을 제어해 고효율 광전소자, 광촉매 및 대면적 양자점 잉크 공정을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      },
      {
        "name": "Jingcheng Wu",
        "nameEn": "Jingcheng Wu",
        "status": "InnoCORE Research Fellow",
        "currentPi": "최창혁 교수 (POSTECH)",
        "researchArea": "에너지 전환 소재",
        "affiliation": "DGIST InnoCORE E-MatAX 연구단",
        "summary": "바이오매스 플랫폼 분자의 전기화학 전환과 환원 반응을 결합한 paired electrolysis를 설계해 고부가 화학물질 생산을 연구합니다.",
        "image": "./assets/fellow-placeholder.svg"
      }
    ],
    openingsKicker: "Fellow Recruitment",
    openingsTitle: "Fellow recruitment notice",
    openingsLead:
      "Applicants can check lab-level hiring status, project fit, preferred expertise, and contact routes beyond the center-wide notice.",
    piOpenings: [
      {
        id: "dong-hae-ho",
        status: "Actively recruiting",
        title: "Postdoctoral Fellow for Liquid Metal Composite Research",
        pi: "Dong Hae Ho",
        lab: "EMDP Lab",
        area: "Liquid metal composite research",
        fit:
          "Seeking a researcher who can work on liquid-metal-based composites, mechanical analysis, and electrical and thermal conductivity characterization. Relevant degree, research passion, careful observation, and comfort with a free research atmosphere are preferred.",
        timeline: "Summer 2027",
        contactLabel: "Contact: hodh123@gmail.com",
        contactHref: "mailto:hodh123@gmail.com",
        heroImage: "./assets/pi-openings/dong-hae-ho-header.png",
        flyer: "./assets/pi-openings/dong-hae-ho-flyer.png",
      },
    ],
    mentorsKicker: "Mentor List",
    mentorsTitle: "E-MatAX mentor group",
    mentorsLead:
      "DGIST and partner faculty cover energy materials, processes, AI, analysis, and validation across the four research pillars.",
    mentorColumns: ["Hiring", "Research Area", "Role", "Name", "English Name", "Affiliation", "Department", "Website"],
    mentorRecruitingStatus: "Actively recruiting",
    mentorDefaultRecruitingStatus: "active",
    mentorRecruitingStatusLabels: {
      active: "Actively recruiting",
      inactive: "Not recruiting",
    },
    mentorRecruitingStatusOptions: [
      { value: "active", label: "Actively recruiting" },
      { value: "inactive", label: "Not recruiting" },
    ],
    mentorRecruitingStatuses: {
      "허수미 교수": "active",
      "고서진 교수": "active",
      "김승현 교수": "active",
      "김영규 교수": "active",
      "김운혁 교수": "active",
      "김진수 교수": "active",
      "김찬연 교수": "active",
      "박인철 교수": "active",
      "박치영 교수": "active",
      "상가라쥬 샨무감 교수": "active",
      "양지웅 교수": "active",
      "이윤구 교수": "active",
      "이종민 교수": "active",
      "이종수 교수": "active",
      "이주혁 교수": "active",
      "이호춘 교수": "active",
      "인수일 교수": "active",
      "장윤희 교수": "active",
      "최승호 교수": "active",
      "최종민 교수": "active",
      "호동해 교수": "active",
      "홍승태 교수": "active",
      "강준희 교수": "active",
      "김대환 책임연구원": "active",
      "김순현 책임연구원": "active",
      "김한슬 교수": "active",
      "남기태 교수": "active",
      "박해선 교수": "active",
      "송현철 교수": "active",
      "이용민 교수": "active",
      "임종우 교수": "active",
      "임종철 교수": "active",
      "최창혁 교수": "active"
    },
    mentorAreas: {
      "허수미 교수": "Materials-Process AI Platform",
      "장윤희 교수": "Materials-Process AI Platform",
      "최승호 교수": "Materials-Process AI Platform",
      "박해선 교수": "Materials-Process AI Platform",
      "강준희 교수": "Materials-Process AI Platform",
      "박인철 교수": "Materials-Process AI Platform",
      "김한슬 교수": "Materials-Process AI Platform",
      "이용민 교수": "Materials-Process AI Platform",
      "이주혁 교수": "Energy Production Materials",
      "고서진 교수": "Energy Production Materials",
      "최종민 교수": "Energy Production Materials",
      "호동해 교수": "Energy Production Materials",
      "이윤구 교수": "Energy Production Materials",
      "김대환 책임연구원": "Energy Production Materials",
      "이종수 교수": "Energy Production Materials",
      "양지웅 교수": "Energy Production Materials",
      "송현철 교수": "Energy Production Materials",
      "임종철 교수": "Energy Production Materials",
      "김찬연 교수": "Energy Conversion Materials",
      "상가라쥬 샨무감 교수": "Energy Conversion Materials",
      "박치영 교수": "Energy Conversion Materials",
      "이종민 교수": "Energy Conversion Materials",
      "김순현 책임연구원": "Energy Conversion Materials",
      "김승현 교수": "Energy Conversion Materials",
      "남기태 교수": "Energy Conversion Materials",
      "최창혁 교수": "Energy Conversion Materials",
      "홍승태 교수": "Energy Storage Materials",
      "김운혁 교수": "Energy Storage Materials",
      "인수일 교수": "Energy Storage Materials",
      "이호춘 교수": "Energy Storage Materials",
      "김진수 교수": "Energy Storage Materials",
      "김영규 교수": "Energy Storage Materials",
      "임종우 교수": "Energy Storage Materials",
    },
    mentors: [
      { role: "Research Director", name: "허수미 교수", nameEn: "Su-Mi Hur", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sml-dgist.vercel.app/" },
      { role: "Mentor", name: "고서진 교수", nameEn: "Seo-Jin Ko", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://hodl.dgist.ac.kr/" },
      { role: "Mentor", name: "김승현 교수", nameEn: "Seunghyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/seunghyeonkimlab/" },
      { role: "Mentor", name: "김영규 교수", nameEn: "Younggyu Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://younggyukim.com" },
      { role: "Mentor", name: "김운혁 교수", nameEn: "Un-Hyuck Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://phduhkim.wixsite.com/my-site-2" },
      { role: "Mentor", name: "김진수 교수", nameEn: "Jinsoo Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://bdpl-website.web.app/" },
      { role: "Mentor", name: "김찬연 교수", nameEn: "Chanyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/ck-researchgroup" },
      { role: "Mentor", name: "박인철 교수", nameEn: "Inchul Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://ai4m.vercel.app" },
      { role: "Mentor", name: "박치영 교수", nameEn: "Chiyoung Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cplab2019.wixsite.com/cplab" },
      { role: "Mentor", name: "상가라쥬 샨무감 교수", nameEn: "Sangaraju Shanmugam", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sangarajus.wixsite.com/shanmugam" },
      { role: "Mentor", name: "양지웅 교수", nameEn: "Jiwoong Yang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://www.jiwoongyang.net" },
      { role: "Mentor", name: "이윤구 교수", nameEn: "Youngu Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://kjy950123.wixsite.com/opel" },
      { role: "Mentor", name: "이종민 교수", nameEn: "Jong-Min Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/jmleedgist/%ED%99%88" },
      { role: "Mentor", name: "이종수 교수", nameEn: "Jong-Soo Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://jslee.dgist.ac.kr/" },
      { role: "Mentor", name: "이주혁 교수", nameEn: "Ju-Hyuck Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://juhyucklee1107.wixsite.com/website" },
      { role: "Mentor", name: "이호춘 교수", nameEn: "Hochun Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://dukelee5.wixsite.com/else" },
      { role: "Mentor", name: "인수일 교수", nameEn: "Suil In", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://insuil.dgist.ac.kr" },
      { role: "Mentor", name: "장윤희 교수", nameEn: "Yun Hee Jang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cmmm.dgist.ac.kr" },
      { role: "Mentor", name: "최승호 교수", nameEn: "Seungho Choe", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://seunghochoe.netlify.app/" },
      { role: "Mentor", name: "최종민 교수", nameEn: "Jongmin Choi", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/choisresearchgroup/home" },
      { role: "Mentor", name: "호동해 교수", nameEn: "Dong Hae Ho", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://emdplab.github.io/" },
      { role: "Mentor", name: "홍승태 교수", nameEn: "Seung-Tae Hong", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sthong.dgist.ac.kr" },
      { role: "Mentor", name: "강준희 교수", nameEn: "Joonhee Kang", affiliation: "Pusan National University", department: "School of Transdisciplinary Engineering", url: "https://sites.google.com/view/kanggroup/home" },
      { role: "Mentor", name: "김대환 책임연구원", nameEn: "Dae-Hwan Kim", affiliation: "DGIST", department: "Department of Interdisciplinary Studies", url: "" },
      { role: "Mentor", name: "김순현 책임연구원", nameEn: "Soonhyun Kim", affiliation: "DGIST", department: "Division of Energy & Environmental Technology", url: "" },
      { role: "Mentor", name: "김한슬 교수", nameEn: "Han Seul Kim", affiliation: "Chungbuk National University", department: "Department of Advanced Materials Engineering", url: "https://atomlab.co.kr/" },
      { role: "Mentor", name: "남기태 교수", nameEn: "Ki Tae Nam", affiliation: "Seoul National University", department: "Department of Materials Science and Engineering", url: "https://www.nkitae.org/" },
      { role: "Mentor", name: "박해선 교수", nameEn: "Haesun Park", affiliation: "Chung-Ang University", department: "School of Integrative Engineering", url: "https://midas-cau.netlify.app/" },
      { role: "Mentor", name: "송현철 교수", nameEn: "Hyun-Cheol Song", affiliation: "Korea University", department: "Department of Materials Science and Engineering", url: "http://eclab.korea.ac.kr/" },
      { role: "Mentor", name: "이용민 교수", nameEn: "Yong Min Lee", affiliation: "Yonsei University", department: "Chemical and Biomolecular Engineering / Battery Engineering", url: "http://batterylab.yonsei.ac.kr/" },
      { role: "Mentor", name: "임종우 교수", nameEn: "Jongwoo Lim", affiliation: "Seoul National University", department: "Department of Chemistry", url: "https://www.jwlimgroup.com" },
      { role: "Mentor", name: "임종철 교수", nameEn: "Jongchul Lim", affiliation: "Chungnam National University", department: "Graduate School of Energy Science and Technology", url: "https://jongchullim.wixsite.com/jclim" },
      { role: "Mentor", name: "최창혁 교수", nameEn: "Chang Hyuck Choi", affiliation: "POSTECH", department: "Department of Chemistry", url: "https://www.ecatlab.com/" },
    ],
    newsKicker: "Recent News",
    newsTitle: "Recruitment and event updates",
    newsLead:
      "Follow official recruitment notices, global job fair schedules, and E-MatAX program announcements.",
    news: [
      {
        "date": "2026.07.20",
        "title": "E-MatAX Luncheon Seminar | 이태훈 교수·E-MatAX Fellow",
        "description": "DGIST 이태훈 교수님과 E-MatAX Postdoctoral Fellow가 함께 런천 세미나를 진행했습니다. 시뮬레이션과 AI 계산과의 징검다리 역할을 할 수 있는 다양한 방법론에 대해 알아보는 자리였습니다.",
        "href": "",
        "images": [
          {
            "thumb": "./assets/news/2026-07-20-luncheon-seminar-thumb.jpg",
            "full": "./assets/news/2026-07-20-luncheon-seminar.jpg"
          }
        ]
      },
      {
        "date": "2026.07.06",
        "title": "E-MatAX Luncheon Seminar | 김영규 교수·E-MatAX Fellow",
        "description": "DGIST 김영규 교수님과 Fellow 박사와 함께 Luncheon 세미나를 진행하였습니다. 실험과 AI 를 이을 수 있는 다양한 방법론에 대한 심도깊은 세미나였습니다",
        "href": "",
        "images": [
          {
            "thumb": "./assets/news/2026-07-06-luncheon-opening-thumb.jpg",
            "full": "./assets/news/2026-07-06-luncheon-opening.jpg"
          },
          {
            "thumb": "./assets/news/2026-07-06-luncheon-kim-younggyu-thumb.jpg",
            "full": "./assets/news/2026-07-06-luncheon-kim-younggyu.jpg"
          },
          {
            "thumb": "./assets/news/2026-07-06-luncheon-audience-thumb.jpg",
            "full": "./assets/news/2026-07-06-luncheon-audience.jpg"
          }
        ]
      },
      {
        "date": "2026.06",
        "title": "Europe InnoCORE Global AI Postdoctoral Job Fair",
        "description": "",
        "href": "https://www.innocore-jobfair.com/",
        "images": []
      },
      {
        "date": "2026.05",
        "title": "US InnoCORE Global AI Postdoctoral Job Fair",
        "description": "",
        "href": "https://www.innocore-jobfair.com/",
        "images": []
      },
      {
        "date": "상시",
        "title": "DGIST InnoCORE Notice Board",
        "description": "",
        "href": "https://www.innocore.or.kr/dgist/notice/sub01",
        "images": []
      }
    ],
    applyKicker: "Fellow Recruitment",
    applyTitle: "From lab to production, powered by AX",
    applyLead:
      "E-MatAX is looking for Fellows who want to design AX for energy materials commercialization. Review the official notice and contact channel for application procedures.",
    applyActions: [
      { label: "Fellow Recruitment Notice", href: "https://www.innocore.or.kr/dgist/notice/sub01", sameTab: true },
      { label: "Contact: innocore@dgist.ac.kr", href: "mailto:innocore@dgist.ac.kr" },
      { label: "Current Center Page", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
    ],
    footerText:
      "DGIST InnoCORE E-MatAX Research Center",
  },
};
