window.INNOCORE_CONTENT = {
  ko: {
    nav: [
      { label: "지원", href: "#how-apply" },
      { label: "사업단", href: "#about" },
      { label: "연구영역", href: "#research" },
      { label: "멘토", href: "#mentors" },
      { label: "Fellow 지원", href: "#fellows" },
    ],
    headerCta: "지원 안내",
    heroEyebrow: "DGIST InnoCORE | 에너지 소재 상용화 AX 연구단",
    heroTitle: "연구실에서 양산까지",
    heroLead:
      "E-MatAX는 에너지 소재의 스케일업 병목을 실험, 분석, AI, 검증의 순환으로 풀어내는 Fellow 주도형 연구 플랫폼입니다.",
    heroPrimary: "Research Fellow 지원",
    heroSecondary: "연구영역 보기",
    facts: [
      { value: "Energy", label: "생산 · 전환 · 저장 소재" },
      { value: "AX", label: "소재-공정 AI 플랫폼" },
      { value: "Co-Lab", label: "DGIST · 대학 · 산업 협업" },
      { value: "5 Years", label: "최대 5년 성장 트랙" },
    ],
    howApplyKicker: "How to Apply",
    howApplyTitle: "Research Fellow 모집 안내",
    howApplyLead:
      "공식 모집 공고에서 지원 자격과 일정을 확인하고, 관심 연구영역의 멘토와 연구 적합성을 논의할 수 있습니다.",
    howApply: [
      { title: "1. 모집 공고 확인", body: "지원 자격, 제출서류, 전형 일정, 계약 조건을 공식 공고에서 확인합니다." },
      { title: "2. 연구영역 매칭", body: "에너지 저장, 전환, 생산, 소재-공정 AI 중 본인의 전문성과 맞는 연구 축을 선택합니다." },
      { title: "3. 멘토 사전 상담", body: "관심 연구영역과 연결되는 교수진의 연구실 정보를 확인하고 연구 적합성을 논의합니다." },
      { title: "4. 지원서 제출", body: "공식 공고 또는 InnoCORE Job Fair 안내에 따라 지원서를 제출합니다." },
    ],
    requirementsTitle: "지원 요건",
    requirements: [
      "이공계 박사학위 소지자 또는 취득 예정자",
      "박사학위 취득 후 5년 이내를 원칙으로 하되, 탁월한 역량 보유자는 예외 심의 가능",
      "전일제 박사후연구원 임용",
      "1년 단위 계약, 평가 후 최대 5년까지 재계약 가능",
      "외국인은 E-3 등 연구활동 비자 발급 요건 충족 필요",
    ],
    aboutKicker: "Why E-MatAX",
    aboutTitle: "상용화 성능을 AX로 다시 설계",
    aboutBody1:
      "에너지 소재는 실험실에서 확보한 성능이 파일럿 또는 양산 전환 과정에서 약화되는 경우가 많습니다. E-MatAX는 소재 조성, 공정 조건, 분석 데이터, AI 모델을 하나의 스케일업 문제로 다룹니다.",
    aboutBody2:
      "InnoCORE Fellow는 연구의 연결축입니다. 도메인 멘토, AI 멘토, 산업 파트너, 분석 인프라를 연결하며 연구성과가 논문을 넘어 검증과 기술이전으로 이어지도록 이끕니다.",
    centerKicker: "About the Center",
    centerTitle: "에너지 소재 상용화 AX 연구단",
    centerLead:
      "E-MatAX는 에너지 소재 상용화 병목을 AX로 줄이기 위해 DGIST, 국내 주요 대학, 산업 파트너를 연결하는 InnoCORE 연구단입니다.",
    director: {
      kicker: "Chief / Research Director",
      name: "Su-mi Hur",
      title: "허수미 교수 | DGIST 에너지공학과",
      body:
        "허수미 연구단장은 에너지 소재, 공정 데이터, AI 모델, 검증 인프라가 하나의 연구 흐름으로 연결되도록 E-MatAX의 연구 방향과 협력 체계를 이끕니다.",
    },
    centerDetails: [
      { label: "Center Name", value: "Center for Energy Materials Commercialization through AI Transformation (AX)" },
      { label: "Korean Name", value: "에너지 소재 상용화 AX 연구단" },
      { label: "Short Name", value: "E-MatAX" },
      { label: "Project Period", value: "Phase I: 2026.05-2028.12 / Phase II: 2029.01-2030.12" },
    ],
    teamsTitle: "Research Teams",
    teams: [
      { title: "Team 1", body: "Energy Storage Materials" },
      { title: "Team 2", body: "Energy Conversion Materials" },
      { title: "Team 3", body: "Energy Production Materials" },
      { title: "Team 4", body: "Materials-Process AI Platform" },
    ],
    relatedLinksTitle: "Related Links",
    relatedLinks: [
      { label: "E-MatAX Research Center", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
      { label: "DGIST InnoCORE notices", href: "https://www.innocore.or.kr/dgist/notice/sub02" },
      { label: "InnoCORE Global Job Fair", href: "https://www.innocore-jobfair.com/" },
    ],
    researchKicker: "Research Portfolio",
    researchTitle: "상용화를 여는 4대 AX 축",
    researchLead: "저장, 전환, 생산 소재와 소재-공정 AI 플랫폼을 연결해 실험실 성능이 제조 단계에서도 유지되도록 연구합니다.",
    research: [
      {
        title: "에너지 저장 소재",
        problem: "배터리 소재는 공정이 커질수록 균일도, 열화, 계면 안정성 문제가 커집니다.",
        solution: "전극, 전해질, 급속충전, 건식 전극 공정 데이터를 연결해 예측 가능한 스케일업 조건을 찾습니다.",
      },
      {
        title: "에너지 전환 소재",
        problem: "촉매와 전기화학 시스템은 실험 조건과 실제 운전 조건 사이의 차이가 큽니다.",
        solution: "반응, 구조, 열화 데이터를 함께 학습해 고효율·저열화 전환 소재 개발을 앞당깁니다.",
      },
      {
        title: "에너지 생산 소재",
        problem: "태양광 등 생산 소재는 효율, 수명, 제조 재현성을 동시에 확보해야 합니다.",
        solution: "소재 설계와 공정 최적화를 AI 기반으로 반복해 생산 단계의 성능 안정성을 높입니다.",
      },
      {
        title: "소재-공정 AI 플랫폼",
        problem: "연구실마다 데이터가 흩어지면 스케일업 예측과 재현 검증이 어려워집니다.",
        solution: "Descriptor, 물리 기반 AI 모델, 데이터 파이프라인, 검증 라이브러리를 통합합니다.",
      },
    ],
    processKicker: "Research Workflow",
    processTitle: "합성·측정·예측·검증",
    processLead:
      "Fellow는 하나의 소재 문제를 정의하고 실험 데이터와 공정 데이터를 연결합니다. AI 예측 결과는 다시 파일럿 검증으로 돌아가며 연구의 다음 조건을 만듭니다.",
    process: [
      "문제 정의",
      "실험 설계",
      "정밀 분석",
      "AI 모델링",
      "스케일업 검증",
      "산업 연계",
    ],
    fellowsKicker: "For Fellows",
    fellowsTitle: "Fellow 주도 연구, 사업단 지원",
    fellowsLead:
      "PI 보조형 포닥이 아닌, Fellow 주도형 연구 체계",
    support: [
      { title: "듀얼 멘토링", body: "도메인 멘토와 AI 멘토가 함께 연구 방향을 설계하고 AX 역량을 강화합니다." },
      { title: "연구 인프라", body: "DGIST의 분석, 제작, 컴퓨팅, 파일럿 연계 인프라를 연구 목적에 맞게 활용합니다." },
      { title: "산학연 Co-Lab", body: "파트너 대학, 연구기관, 산업 파트너와 함께 실증과 기술이전 가능성을 높입니다." },
      { title: "정주 지원", body: "비자, 온보딩, 생활 정착 지원으로 글로벌 연구자가 빠르게 연구에 집중할 수 있게 돕습니다." },
    ],
    mentorsKicker: "Mentor List",
    mentorsTitle: "E-MatAX 멘토 그룹",
    mentorsLead:
      "DGIST와 국내 주요 대학의 참여 교수진이 에너지 소재, 공정, AI, 분석, 검증 연구를 함께 이끕니다.",
    mentorColumns: ["역할", "성명", "English Name", "소속", "학과/부서", "Website"],
    mentors: [
      { role: "Research Director", name: "허수미 교수", nameEn: "Su-Mi Hur", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sml-dgist.vercel.app/" },
      { role: "Mentor", name: "고서진 교수", nameEn: "Seo-Jin Ko", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://hodl.dgist.ac.kr/" },
      { role: "Mentor", name: "김승현 교수", nameEn: "Seunghyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/seunghyeonkimlab/" },
      { role: "Mentor", name: "김영규 교수", nameEn: "Younggyu Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://younggyukim.com" },
      { role: "Mentor", name: "김운혁 교수", nameEn: "Un-Hyuck Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://phduhkim.wixsite.com/my-site-2" },
      { role: "Mentor", name: "김진수 교수", nameEn: "Jinsoo Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://bdpl-website.web.app/" },
      { role: "Mentor", name: "김찬연 교수", nameEn: "Chanyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/ck-researchgroup" },
      { role: "Mentor", name: "박인철 교수", nameEn: "Inchul Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://ai4m.vercel.app" },
      { role: "Mentor", name: "박치영 교수", nameEn: "Chiyoung Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cplab2019.wixsite.com/cplab" },
      { role: "Mentor", name: "상가라쥬 샨무감 교수", nameEn: "Sangaraju Shanmugam", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sangarajus.wixsite.com/shanmugam" },
      { role: "Mentor", name: "양지웅 교수", nameEn: "Jiwoong Yang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://www.jiwoongyang.net" },
      { role: "Mentor", name: "이윤구 교수", nameEn: "Youngu Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://kjy950123.wixsite.com/opel" },
      { role: "Mentor", name: "이종민 교수", nameEn: "Jong-Min Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/jmleedgist/%ED%99%88" },
      { role: "Mentor", name: "이종수 교수", nameEn: "Jong-Soo Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://jslee.dgist.ac.kr/" },
      { role: "Mentor", name: "이주혁 교수", nameEn: "Ju-Hyuck Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://juhyucklee1107.wixsite.com/website" },
      { role: "Mentor", name: "이호춘 교수", nameEn: "Hochun Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://dukelee5.wixsite.com/else" },
      { role: "Mentor", name: "인수일 교수", nameEn: "Suil In", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://insuil.dgist.ac.kr" },
      { role: "Mentor", name: "장윤희 교수", nameEn: "Yun Hee Jang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cmmm.dgist.ac.kr" },
      { role: "Mentor", name: "최승호 교수", nameEn: "Seungho Choe", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://seunghochoe.netlify.app/" },
      { role: "Mentor", name: "최종민 교수", nameEn: "Jongmin Choi", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/choisresearchgroup/home" },
      { role: "Mentor", name: "호동해 교수", nameEn: "Dong Hae Ho", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://emdplab.github.io/" },
      { role: "Mentor", name: "홍승태 교수", nameEn: "Seung-Tae Hong", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sthong.dgist.ac.kr" },
      { role: "Mentor", name: "강준희 교수", nameEn: "Joonhee Kang", affiliation: "Pusan National University", department: "School of Transdisciplinary Engineering", url: "https://sites.google.com/view/kanggroup/home" },
      { role: "Mentor", name: "김대환 책임연구원", nameEn: "Dae-Hwan Kim", affiliation: "DGIST", department: "Department of Interdisciplinary Studies", url: "" },
      { role: "Mentor", name: "김순현 책임연구원", nameEn: "Soonhyun Kim", affiliation: "DGIST", department: "Division of Energy & Environmental Technology", url: "" },
      { role: "Mentor", name: "김한슬 교수", nameEn: "Han Seul Kim", affiliation: "Chungbuk National University", department: "Department of Advanced Materials Engineering", url: "https://atomlab.co.kr/" },
      { role: "Mentor", name: "남기태 교수", nameEn: "Ki Tae Nam", affiliation: "Seoul National University", department: "Department of Materials Science and Engineering", url: "https://www.nkitae.org/" },
      { role: "Mentor", name: "박해선 교수", nameEn: "Haesun Park", affiliation: "Chung-Ang University", department: "School of Integrative Engineering", url: "https://midas-cau.netlify.app/" },
      { role: "Mentor", name: "송현철 교수", nameEn: "Hyun-Cheol Song", affiliation: "Korea University", department: "Department of Materials Science and Engineering", url: "http://eclab.korea.ac.kr/" },
      { role: "Mentor", name: "이용민 교수", nameEn: "Yong Min Lee", affiliation: "Yonsei University", department: "Chemical and Biomolecular Engineering / Battery Engineering", url: "http://batterylab.yonsei.ac.kr/" },
      { role: "Mentor", name: "임종우 교수", nameEn: "Jongwoo Lim", affiliation: "Seoul National University", department: "Department of Chemistry", url: "https://www.jwlimgroup.com" },
      { role: "Mentor", name: "임종철 교수", nameEn: "Jongchul Lim", affiliation: "Chungnam National University", department: "Graduate School of Energy Science and Technology", url: "https://jongchullim.wixsite.com/jclim" },
      { role: "Mentor", name: "최창혁 교수", nameEn: "Chang Hyuck Choi", affiliation: "POSTECH", department: "Department of Chemistry", url: "https://www.ecatlab.com/" },
    ],
    newsKicker: "Recent News",
    newsTitle: "공고 및 행사 소식",
    newsLead:
      "Research Fellow 모집 공고와 글로벌 Job Fair 일정을 확인할 수 있습니다.",
    news: [
      { date: "2026.06", title: "Europe InnoCORE Global AI Postdoctoral Job Fair", href: "https://www.innocore-jobfair.com/" },
      { date: "2026.05", title: "US InnoCORE Global AI Postdoctoral Job Fair", href: "https://www.innocore-jobfair.com/" },
      { date: "상시", title: "DGIST InnoCORE Notice Board", href: "https://www.innocore.or.kr/dgist/notice/sub02" },
    ],
    applyKicker: "Recruitment",
    applyTitle: "AX로 실험실에서 양산까지",
    applyLead:
      "E-MatAX와 함께 에너지 소재 상용화 AX를 만들어갈 Research Fellow를 모집합니다. 공식 모집 공고와 문의 채널을 통해 지원 절차를 확인해주세요.",
    applyActions: [
      { label: "모집 공고 바로가기", href: "https://www.innocore.or.kr/dgist/notice/sub02" },
      { label: "문의: innocore@dgist.ac.kr", href: "mailto:innocore@dgist.ac.kr" },
      { label: "E-MatAX 연구단 소개", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
    ],
    footerText:
      "DGIST InnoCORE E-MatAX Research Center",
  },
  en: {
    nav: [
      { label: "Apply", href: "#how-apply" },
      { label: "About", href: "#about" },
      { label: "Research", href: "#research" },
      { label: "Mentors", href: "#mentors" },
      { label: "Fellows", href: "#fellows" },
    ],
    headerCta: "Apply",
    heroEyebrow: "DGIST InnoCORE | E-MatAX Research Center",
    heroTitle: "Fellow-led AX, from lab to production",
    heroLead:
      "E-MatAX reduces scale-up bottlenecks in energy production, conversion, and storage materials through an experiment-analysis-AI-validation loop while training next-generation convergence researchers.",
    heroPrimary: "Application Guide",
    heroSecondary: "Research Scope",
    facts: [
      { value: "Energy", label: "Production, conversion, storage" },
      { value: "AX", label: "Materials-process AI platform" },
      { value: "Co-Lab", label: "DGIST, universities, industry" },
      { value: "5 Years", label: "Up to five-year growth track" },
    ],
    howApplyKicker: "How to Apply",
    howApplyTitle: "Fellow application guide",
    howApplyLead:
      "Review the notice, choose a research area, and discuss fit with mentors.",
    howApply: [
      { title: "1. Check the notice", body: "Review eligibility, required documents, and timeline through the official announcement and FAQ." },
      { title: "2. Choose a research area", body: "Find the best fit across energy storage, conversion, production, or the materials-process AI platform." },
      { title: "3. Contact mentors", body: "Review labs connected to your research interests and arrange early conversations where appropriate." },
      { title: "4. Submit application", body: "Apply through the finalized official notice or InnoCORE Job Fair channel." },
    ],
    requirementsTitle: "Requirements",
    requirements: [
      "Ph.D. degree in science or engineering, obtained or expected",
      "Generally within five years of Ph.D. conferral, with exceptional-candidate review possible",
      "Full-time postdoctoral appointment",
      "One-year contract, renewable for up to five years subject to evaluation",
      "International applicants must satisfy research visa requirements such as E-3",
    ],
    aboutKicker: "Why E-MatAX",
    aboutTitle: "Scale-up performance with AX",
    aboutBody1:
      "Energy materials often lose lab-scale performance when they move into pilot and manufacturing environments. E-MatAX treats composition, process conditions, characterization data, and AI models as one integrated scale-up problem.",
    aboutBody2:
      "InnoCORE Fellows act as the connective core of research. Fellows link domain mentors, AI mentors, industry partners, and research infrastructure so that outcomes move beyond papers toward validation and technology transfer.",
    centerKicker: "About the Center",
    centerTitle: "E-MatAX Research Center",
    centerLead:
      "E-MatAX connects DGIST, partner universities, and industry to solve energy-materials scale-up bottlenecks.",
    director: {
      kicker: "Chief / Research Director",
      name: "Su-mi Hur",
      title: "Professor, Department of Energy Science and Engineering, DGIST",
      body:
        "The E-MatAX chief leads the center's research direction and collaboration across energy materials, process data, AI models, and validation infrastructure.",
    },
    centerDetails: [
      { label: "Center Name", value: "Energy Materials Commercialization through AI Transformation (AX)" },
      { label: "Korean Name", value: "에너지 소재 상용화 AX 연구단" },
      { label: "Short Name", value: "E-MatAX" },
      { label: "Project Period", value: "Phase I: May 2026-Dec. 2028 / Phase II: Jan. 2029-Dec. 2030" },
    ],
    teamsTitle: "Research Teams",
    teams: [
      { title: "Team 1", body: "Energy Storage Materials" },
      { title: "Team 2", body: "Energy Conversion Materials" },
      { title: "Team 3", body: "Energy Production Materials" },
      { title: "Team 4", body: "Materials-Process AI Platform" },
    ],
    relatedLinksTitle: "Related Links",
    relatedLinks: [
      { label: "E-MatAX Research Center", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
      { label: "DGIST InnoCORE notices", href: "https://www.innocore.or.kr/dgist/notice/sub02" },
      { label: "InnoCORE Global Job Fair", href: "https://www.innocore-jobfair.com/" },
    ],
    researchKicker: "Research Portfolio",
    researchTitle: "Four AX research pillars",
    researchLead: "Storage, conversion, production, and AI-platform research keep lab performance viable at manufacturing scale.",
    research: [
      {
        title: "Energy Storage Materials",
        problem: "Battery materials face uniformity, degradation, and interface stability challenges during scale-up.",
        solution: "We connect electrode, electrolyte, fast-charging, and dry-electrode process data to find predictable scale-up conditions.",
      },
      {
        title: "Energy Conversion Materials",
        problem: "Catalysts and electrochemical systems often show a gap between laboratory tests and real operating conditions.",
        solution: "We jointly learn reaction, structure, and degradation data to accelerate high-efficiency, low-degradation materials.",
      },
      {
        title: "Energy Production Materials",
        problem: "Solar and next-generation production materials must balance efficiency, lifetime, and manufacturing reproducibility.",
        solution: "We iterate AI-driven material design and process optimization to improve performance stability at production scale.",
      },
      {
        title: "Materials-Process AI Platform",
        problem: "Scattered data makes scale-up prediction and reproducibility checks difficult.",
        solution: "We integrate descriptors, physics-informed models, data pipelines, and validation libraries.",
      },
    ],
    processKicker: "Research Workflow",
    processTitle: "Make. Measure. Predict. Validate.",
    processLead:
      "E-MatAX is organized around the research loop, not administrative wording. Fellows define a material problem, connect experiment and process data, use AI prediction, and return the result to pilot-scale validation.",
    process: [
      "Problem framing",
      "Experiment design",
      "Characterization",
      "AI modeling",
      "Scale-up validation",
      "Industry linkage",
    ],
    fellowsKicker: "For Fellows",
    fellowsTitle: "Independent Fellows, structured support",
    fellowsLead:
      "This is not a standard PI-assistant postdoc model. Fellows define problems and organize collaboration.",
    support: [
      { title: "Dual Mentoring", body: "Domain and AI mentors help Fellows strengthen both energy materials expertise and AX capability." },
      { title: "Infrastructure Access", body: "Fellows use DGIST characterization, fabrication, computing, and pilot-linked infrastructure for research goals." },
      { title: "Industry Co-Lab", body: "Partner universities, research institutes, and industry partners increase the chance of demonstration and transfer." },
      { title: "Settlement Support", body: "Visa, onboarding, and relocation support help global researchers focus on research quickly." },
    ],
    mentorsKicker: "Mentor List",
    mentorsTitle: "E-MatAX mentor group",
    mentorsLead:
      "DGIST and partner faculty cover energy materials, processes, AI, analysis, and validation.",
    mentorColumns: ["Role", "Name", "English Name", "Affiliation", "Department", "Website"],
    mentors: [
      { role: "Research Director", name: "허수미 교수", nameEn: "Su-Mi Hur", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sml-dgist.vercel.app/" },
      { role: "Mentor", name: "고서진 교수", nameEn: "Seo-Jin Ko", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://hodl.dgist.ac.kr/" },
      { role: "Mentor", name: "김승현 교수", nameEn: "Seunghyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/seunghyeonkimlab/" },
      { role: "Mentor", name: "김영규 교수", nameEn: "Younggyu Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://younggyukim.com" },
      { role: "Mentor", name: "김운혁 교수", nameEn: "Un-Hyuck Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://phduhkim.wixsite.com/my-site-2" },
      { role: "Mentor", name: "김진수 교수", nameEn: "Jinsoo Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://bdpl-website.web.app/" },
      { role: "Mentor", name: "김찬연 교수", nameEn: "Chanyeon Kim", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/ck-researchgroup" },
      { role: "Mentor", name: "박인철 교수", nameEn: "Inchul Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://ai4m.vercel.app" },
      { role: "Mentor", name: "박치영 교수", nameEn: "Chiyoung Park", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cplab2019.wixsite.com/cplab" },
      { role: "Mentor", name: "상가라쥬 샨무감 교수", nameEn: "Sangaraju Shanmugam", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sangarajus.wixsite.com/shanmugam" },
      { role: "Mentor", name: "양지웅 교수", nameEn: "Jiwoong Yang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://www.jiwoongyang.net" },
      { role: "Mentor", name: "이윤구 교수", nameEn: "Youngu Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://kjy950123.wixsite.com/opel" },
      { role: "Mentor", name: "이종민 교수", nameEn: "Jong-Min Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/jmleedgist/%ED%99%88" },
      { role: "Mentor", name: "이종수 교수", nameEn: "Jong-Soo Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://jslee.dgist.ac.kr/" },
      { role: "Mentor", name: "이주혁 교수", nameEn: "Ju-Hyuck Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://juhyucklee1107.wixsite.com/website" },
      { role: "Mentor", name: "이호춘 교수", nameEn: "Hochun Lee", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://dukelee5.wixsite.com/else" },
      { role: "Mentor", name: "인수일 교수", nameEn: "Suil In", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://insuil.dgist.ac.kr" },
      { role: "Mentor", name: "장윤희 교수", nameEn: "Yun Hee Jang", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://cmmm.dgist.ac.kr" },
      { role: "Mentor", name: "최승호 교수", nameEn: "Seungho Choe", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://seunghochoe.netlify.app/" },
      { role: "Mentor", name: "최종민 교수", nameEn: "Jongmin Choi", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sites.google.com/view/choisresearchgroup/home" },
      { role: "Mentor", name: "호동해 교수", nameEn: "Dong Hae Ho", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://emdplab.github.io/" },
      { role: "Mentor", name: "홍승태 교수", nameEn: "Seung-Tae Hong", affiliation: "DGIST", department: "Department of Energy Science and Engineering", url: "https://sthong.dgist.ac.kr" },
      { role: "Mentor", name: "강준희 교수", nameEn: "Joonhee Kang", affiliation: "Pusan National University", department: "School of Transdisciplinary Engineering", url: "https://sites.google.com/view/kanggroup/home" },
      { role: "Mentor", name: "김대환 책임연구원", nameEn: "Dae-Hwan Kim", affiliation: "DGIST", department: "Department of Interdisciplinary Studies", url: "" },
      { role: "Mentor", name: "김순현 책임연구원", nameEn: "Soonhyun Kim", affiliation: "DGIST", department: "Division of Energy & Environmental Technology", url: "" },
      { role: "Mentor", name: "김한슬 교수", nameEn: "Han Seul Kim", affiliation: "Chungbuk National University", department: "Department of Advanced Materials Engineering", url: "https://atomlab.co.kr/" },
      { role: "Mentor", name: "남기태 교수", nameEn: "Ki Tae Nam", affiliation: "Seoul National University", department: "Department of Materials Science and Engineering", url: "https://www.nkitae.org/" },
      { role: "Mentor", name: "박해선 교수", nameEn: "Haesun Park", affiliation: "Chung-Ang University", department: "School of Integrative Engineering", url: "https://midas-cau.netlify.app/" },
      { role: "Mentor", name: "송현철 교수", nameEn: "Hyun-Cheol Song", affiliation: "Korea University", department: "Department of Materials Science and Engineering", url: "http://eclab.korea.ac.kr/" },
      { role: "Mentor", name: "이용민 교수", nameEn: "Yong Min Lee", affiliation: "Yonsei University", department: "Chemical and Biomolecular Engineering / Battery Engineering", url: "http://batterylab.yonsei.ac.kr/" },
      { role: "Mentor", name: "임종우 교수", nameEn: "Jongwoo Lim", affiliation: "Seoul National University", department: "Department of Chemistry", url: "https://www.jwlimgroup.com" },
      { role: "Mentor", name: "임종철 교수", nameEn: "Jongchul Lim", affiliation: "Chungnam National University", department: "Graduate School of Energy Science and Technology", url: "https://jongchullim.wixsite.com/jclim" },
      { role: "Mentor", name: "최창혁 교수", nameEn: "Chang Hyuck Choi", affiliation: "POSTECH", department: "Department of Chemistry", url: "https://www.ecatlab.com/" },
    ],
    newsKicker: "Recent News",
    newsTitle: "Recruitment and event updates",
    newsLead:
      "Follow official recruitment notices, global job fair schedules, and E-MatAX program announcements.",
    news: [
      { date: "2026.06", title: "Europe InnoCORE Global AI Postdoctoral Job Fair", href: "https://www.innocore-jobfair.com/" },
      { date: "2026.05", title: "US InnoCORE Global AI Postdoctoral Job Fair", href: "https://www.innocore-jobfair.com/" },
      { date: "Always", title: "DGIST InnoCORE Notice Board", href: "https://www.innocore.or.kr/dgist/notice/sub02" },
    ],
    applyKicker: "Recruitment",
    applyTitle: "From lab to production, powered by AX",
    applyLead:
      "E-MatAX is looking for Fellows who want to design AX for energy materials commercialization. Review the official notice and contact channel for application procedures.",
    applyActions: [
      { label: "Recruitment Notice", href: "https://www.innocore.or.kr/dgist/notice/sub02" },
      { label: "Contact: innocore@dgist.ac.kr", href: "mailto:innocore@dgist.ac.kr" },
      { label: "Current Center Page", href: "https://www.innocore.or.kr/dgist/dgistLab/drsch_rsch02" },
    ],
    footerText:
      "DGIST InnoCORE E-MatAX Research Center",
  },
};
